config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#top"
  get "home/about"
  get 'home/thanks' => 'home#thanks', as: 'thanks'


  devise_for :admin
  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      member do
        patch 'restore'
      end
    end
    resources :lawyers, only: [:index, :show, :destroy] do
      member do
        patch 'restore'
      end
    end
    resources :categories, only: [:index, :create, :edit, :update]
    resources :comments, only: [:destroy]
    resources :troubles, only: [:destroy]
    resources :inquiries, only: [:index, :show, :destroy]
  end


  devise_for :lawyers, :controllers => {
  :registrations => 'lawyers/registrations'
  }
  scope module: :lawyers do
    get 'lawyers/:id/withdraw' => 'lawyers#withdraw',as: 'lawyer_withdraw'
    get 'lawyers/:id/map' => 'map#show',as: 'map'
    resources :lawyers, only: [:show, :edit, :update, :destroy]
    resources :comments, only: [:new, :create] do
      collection do
        get :confirm
        post :confirm
        post :new, path: :new, as: :new, action: :back
      end
    end
  end


  devise_for :users, :controllers => {
  :registrations => 'users/registrations'
  }
  scope module: :users do
    get 'users/:id/withdraw' => 'users#withdraw',as: 'user_withdraw'
    resources :troubles, only: [:index, :new, :create, :show] do
      collection do
        get :confirm
        post :confirm
        post :new, path: :new, as: :new, action: :back
      end
    end
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :comments, only: [] do
      resource :references, only: [:create, :destroy]
    end
    resources :references, only: [:index]
  end

    resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
    resources :inquiries, only: [:new, :create] do
      collection do
        get :thanks
      end
  end


end

app/models/lawyer.rb
class Lawyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  has_many :comments
  has_many :rooms

  enum profession: {弁護士:1, 司法書士:2, 行政書士:3, 会計士:4, 税理士:5}
  enum age: {二十歳代:1, 三十歳代:2, 四十歳代:3, 五十歳代:4, 六十歳以上:5 }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :office, presence: true
  validates :profession, presence: true
  validates :sex, inclusion: { in: [true, false] }
  validates :age, presence: true
  validates :profile, length: { maximum: 50 }
  validates :postal_code, presence: true, length: { is: 7 }
  validates :prefecture, presence: true
  validates :address, presence: true
  validates :phone_number, length: { minimum: 10, maximum: 11 }, allow_blank: true
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true

  acts_as_paranoid
end

app/controllers/admin/lawyers_controller.rb
class Admin::LawyersController < ApplicationController

    before_action :authenticate_admin!

    def index
       @lawyers = Lawyer.all.with_deleted.order(created_at: :desc).page(params[:page]).per(10)
       @lawyer_all = Lawyer.all.with_deleted
    end

    def show
       @lawyer = Lawyer.with_deleted.find(params[:id])
    end

    def restore
       @lawyer = Lawyer.with_deleted.find(params[:id])
       @lawyer.restore
       redirect_to admin_lawyer_path(@lawyer)
    end

    def destroy
       @lawyer = Lawyer.with_deleted.find(params[:id])
       @lawyer.destroy
       redirect_to admin_lawyer_path(@lawyer)
    end

end

app/controllers/lawyers/comments_controller.rb
class Lawyers::CommentsController < ApplicationController

    before_action :lawyer_new, only: [:new]
    before_action :lawyer_create, only:[:confirm, :create, :back]

    def new
       @comment = Comment.new
       @trouble = Trouble.find(params[:trouble_id])
       @comment.trouble_id = params[:trouble_id]
    end

    def confirm
       @comment = Comment.new(comment_params)
       @comment.lawyer_id = current_lawyer.id
       return if @comment.valid?
         @trouble = Trouble.find(@comment.trouble_id)
         render :new
    end

    def back
       @comment = Comment.new(comment_params)
       @trouble = Trouble.find(@comment.trouble_id)
       render :new
    end

    def create
       @comment = Comment.new(comment_params)
       @comment.lawyer_id = current_lawyer.id
         if @comment.save
         	redirect_to trouble_path(@comment.trouble_id)
         else
         	render 'confirm'
         end
    end

    private
      def comment_params
      	 params.require(:comment).permit(:comment, :trouble_id)
      end

      def lawyer_new
      	trouble = Trouble.find(params[:trouble_id])
      	if lawyer_signed_in?
      	  if trouble.user.deleted_at == nil
      	    #回答は一人一度限りを設定
      	  	if Comment.exists?(trouble_id: trouble.id, lawyer_id: current_lawyer.id)
      	  	  redirect_to trouble_path(trouble)
      	    end
      	  else
      	  	redirect_to trouble_path(trouble)
      	  end
        else
      	  redirect_to troubles_path
      	end
      end

      def lawyer_create
      	comment = Comment.new(comment_params)
      	trouble = Trouble.find(comment.trouble_id)
      	if lawyer_signed_in?
      	  if trouble.user.deleted_at == nil
      	    #回答は一人一度限りを設定
      	    if Comment.exists?(trouble_id: trouble.id, lawyer_id: current_lawyer.id)
      	  	  redirect_to trouble_path(trouble)
      	    end
      	  else
      	  	redirect_to trouble_path(trouble)
      	  end
        else
      	  redirect_to troubles_path
      	end
      end

end

app/controllers/lawyers/confirmations_controller.rb
# frozen_string_literal: true

class Lawyers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/lawyers/lawyers_controller.rb
class Lawyers::LawyersController < ApplicationController

    before_action :correct_lawyer, only: [:edit, :update, :withdraw, :destroy]
    before_action :login_model, only: [:show]

    def show
       @lawyer = Lawyer.with_deleted.find(params[:id])
       @true_comments = []
       reference = []
         @lawyer.comments.order(created_at: :desc).each do |comment|
           if comment.trouble.category.is_active == true
             @true_comments << comment
             reference << comment.references.count
             @true_references = reference.sum
           end
       end
       @comments = Kaminari.paginate_array(@true_comments).page(params[:page]).per(15)
    end

    def edit
       @lawyer = Lawyer.find(current_lawyer.id)
    end

    def update
       @lawyer = Lawyer.find(current_lawyer.id)
         if @lawyer.update(lawyer_params)
           redirect_to lawyer_path(current_lawyer)
         else
           render 'edit'
         end
    end

    def withdraw
    end

    def destroy
       lawyer = Lawyer.find(current_lawyer.id)
       lawyer.destroy
       redirect_to thanks_path
    end

    private
      def lawyer_params
        params.require(:lawyer).permit(:name, :name_kana, :office, :profession, :age, :postal_code, :prefecture, :address, :latitude, :longitude, :profile, :phone_number, :url, :image, :email)
      end

      def correct_lawyer
        lawyer = Lawyer.find(params[:id])
          if lawyer_signed_in?
            if current_lawyer.id != lawyer.id
              redirect_to edit_lawyer_path(current_lawyer)
            end
          elsif user_signed_in?
              redirect_to edit_user_path(current_user)
          else
              redirect_to root_path
          end
      end

      def login_model
        lawyer = Lawyer.with_deleted.find(params[:id])
          if lawyer.deleted_at == nil
            if lawyer_signed_in?
              if current_lawyer.id != lawyer.id
                redirect_to lawyer_path(current_lawyer)
              end
            elsif user_signed_in?
                rooms = current_user.rooms
                #自分が入ってるroomの相手のidを格納する
                @lawyer_ids = []
                   rooms.each do |room|
                   @lawyer_ids << room.lawyer_id
                end
            elsif admin_signed_in?
            else
                redirect_to root_path
            end
          else
            if lawyer_signed_in?
                redirect_to lawyer_path(current_lawyer)
            elsif user_signed_in?
                redirect_to user_path(current_user)
            elsif admin_signed_in?
            else
                redirect_to root_path
            end
          end
      end

end

app/controllers/lawyers/map_controller.rb
class Lawyers::MapController < ApplicationController

    before_action :login_model, only: [:show]

    def show
       @lawyer = Lawyer.with_deleted.find(params[:id])
    end


    private
      def login_model
        lawyer = Lawyer.with_deleted.find(params[:id])
          if lawyer.deleted_at == nil
    	    unless user_signed_in? || admin_signed_in?
    	    	if lawyer_signed_in?
    	    	  if current_lawyer.id != lawyer.id
    	    	  	redirect_to lawyer_path(current_lawyer)
    	    	  end
    	    	else
    	          redirect_to root_path
    	        end
          end
          else
            unless admin_signed_in?
              if lawyer_signed_in?
                redirect_to lawyer_path(current_lawyer)
              elsif user_signed_in?
                redirect_to user_path(current_user)
              else
                redirect_to root_path
              end
            end
          end
      end
end

app/controllers/lawyers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Lawyers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/lawyers/passwords_controller.rb
# frozen_string_literal: true

class Lawyers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/lawyers/registrations_controller.rb
# frozen_string_literal: true

class Lawyers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :office, :profession, :sex, :age, :postal_code, :prefecture, :address, :latitude, :longitude, :phone_number, :url])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/lawyers/sessions_controller.rb
# frozen_string_literal: true

class Lawyers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/lawyers/unlocks_controller.rb
# frozen_string_literal: true

class Lawyers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/lawyers_helper.rb
module Admin::LawyersHelper
end

app/helpers/lawyers/comments_helper.rb
module Lawyers::CommentsHelper
end

app/helpers/lawyers/lawyers_helper.rb
module Lawyers::LawyersHelper
end

app/helpers/lawyers/map_helper.rb
module Lawyers::MapHelper
end

app/views/lawyers/lawyers/_info.html.erb
<table ~~~ class = "table text-center">

  <colgroup>
     <col style = "width:25%;">
     <col style = "width:75%;">
  </colgroup>

    <tr>
      <th>写真</th>
      <td><%= attachment_image_tag lawyer, :image, :fill, 200, 200, fallback: "no_image.jpg", size:'150x150' %></td>
    </tr>
    <tr>
      <th>姓・名</th>
      <td><%= lawyer.name %></td>
    </tr>
    <tr>
      <th>かな</th>
      <td><%= lawyer.name_kana %></td>
    </tr>
    <tr>
      <th>職業</th>
      <td><%= lawyer.profession %></td>
    </tr>
    <tr>
      <th>事務所</th>
      <td><%= lawyer.office %></td>
    </tr>
    <tr>
      <th>事務所場所</th>
      <td><%= link_to '事務所の場所を見る', map_path(lawyer), class: "each_link" %></td>
    </tr>
    <tr>
      <th>性別</th>
      <td>
          <% if lawyer.sex == true %>
            男性
          <% else %>
            女性
          <% end %>
      </td>
    </tr>
    <tr>
      <th>年齢</th>
      <td><%= lawyer.age %></td>
    </tr>
    <tr>
      <th>都道府県</th>
      <td><%= lawyer.prefecture %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= lawyer.address %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= lawyer.phone_number %></td>
    </tr>
    <tr>
      <th>URL</th>
      <td><%= link_to lawyer.url, :target=>["_blank"], class: "each_link" do %><%= lawyer.url %><% end %></td>
    </tr>
    <tr>
      <th>自己紹介</th>
      <td class="text-left"><%= lawyer.profile %></td>
    </tr>

</table></br>

<div class="col-xs-10 col-xs-offset-1">

  <% if lawyer_signed_in? %>
    <% if current_lawyer.id == lawyer.id %>
      <%= link_to '編集する', edit_lawyer_path, class: "btn btn-success col-xs-12" %>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.chat(lawyer.id).count != 0 %>
      <% if @lawyer_ids.include?(lawyer.id) %>
        <%= link_to "直接相談する", room_path(current_user.rooms.find_by(lawyer_id: lawyer.id)), class: "btn btn-warning col-xs-12" %><br>
      <% else %>
        <%= form_for Room.new do |f| %>
          <%= f.hidden_field :lawyer_id, :value => lawyer.id %>
          <%= f.submit "直接相談する", class: "btn btn-warning col-xs-12" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %><br/><br/><br/>

</div>

app/views/lawyers/lawyers/_list.html.erb
<% if trues.count == 0 %>

  <% if lawyer_signed_in? && current_lawyer.id == lawyer.id %>
    <div class="col-xs-12 center">
      <h2>相談への回答投稿は、まだしていません</h2>
    </div>
  <% else %>
    <div class="col-xs-12 center">
      <h2>このユーザーの回答投稿は０件です</h2>
    </div>
  <% end %>

<% else %>

  <h3 style="text-decoration: underline">回答件数 <%= trues.count %>件（"<span class="glyphicon glyphicon-thumbs-up"></span>参考になった"が<%= references %>件ついています）</h3></br>

  <div class="col-xs-10 col-xs-offset-1">
    <h4>ー<%= comments.count %>件を表示中ー（投稿の新しい順）</h4>
  </div><br/>

  <table ~~~ class = "table">

    <colgroup>
       <col style = "width:20%;">
       <col style = "width:80%;">
    </colgroup>

    <tr class= "tr-color">
  	<th class = "text-center">カテゴリー</th>
  	<th>タイトル</th>
    </tr>

  <% comments.each do |comment| %>
    <tr>
  	<td class = "text-center">
      <%= comment.trouble.category.name %>
  	</td>
  	<td>
      <%= link_to trouble_path(comment.trouble_id), class: "each_link" do%>
        <%= comment.comment.truncate(36) %>
      <% end %>
  	</td>
    </tr>
  <%end%>

  </table>

  <div class = "col-xs-12 center"><br/>
    <%= paginate comments, class: "paginate" %>
  </div>

<% end %>

app/views/lawyers/lawyers/edit.html.erb
<div class="container yield">
  <div class="row">

    <div class="col-xs-6 col-xs-offset-3">
      <h2><span class="subject">&nbsp;&nbsp;&nbsp;ユーザー情報を編集する&nbsp;&nbsp;&nbsp;</span></h2><br/>
    </div>

    <div class="col-xs-10 col-xs-offset-3">

      <div>
        <% if @lawyer.errors.any? %>
          <div class= "error">
            <div id="error_explanation">
              <h3>
                <%= pluralize(@lawyer.errors.count, "error") %>
                prohibited this lawyer from being saved:
              </h3>
                <% @lawyer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <%= form_for(current_lawyer) do |f| %>

        <div class="field">
          <%= f.label :メールアドレス %> <span class="required">※必須</span><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"col-xs-3" %>
        </div></br></br>

        <div class="field">
          <%= f.label :名前（姓・名） %> <span class="required">※必須</span>（姓・名の間に一文字スペースをご入力願います）<br />
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"col-xs-2"%>
        </div></br></br>

        <div class="field">
          <%= f.label :名前（せい・めい） %> <span class="required">※必須</span>（せい・めいの間に一文字スペースをご入力願います）<br />
          <%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana", class:"col-xs-2"%>
        </div></br></br>

        <div class="field">
          <%= f.label :事務所の名前 %> <span class="required">※必須</span><br />
          <%= f.text_field :office, autofocus: true, autocomplete: "office", class:"col-xs-3"%>
        </div></br></br>

        <div class="field">
          <%= f.label :職業 %> <span class="required">※必須</span><br />
          <%= f.select :profession, Lawyer.professions.keys.to_a, :prompt => "--選択--" %>
        </div></br>

        <div class="field">
          <%= f.label :年齢 %> <span class="required">※必須</span><br />
          <%= f.select :age, Lawyer.ages.keys.to_a, :prompt => "--選択--" %>
        </div></br>

        <div class="field">
          <%= f.label :郵便番号 %>（ハイフン無しで半角数字のみ、ご入力願います）<span class="required">※必須</span><br />
          <%= f.text_field :postal_code, class:"col-xs-2" %>
        </div></br></br>

        <div class="field">
          <%= f.label :県 %> <span class="required">※必須</span><br />
          <%= f.collection_select :prefecture, JpPrefecture::Prefecture.all, :name, :name %>
        </div></br>

        <div class="field">
          <%= f.label :市以下の住所 %> <span class="required">※必須</span><br />
          <%= f.text_field :address, class:"col-xs-5"%>
        </div></br></br>

        <div class = "field">
          <%= f.label :電話番号 %>（ハイフン無しで半角数字のみ、ご入力願います） <span class="recommendation">推奨</span><br/>
          <%= f.text_field :phone_number, class:"col-xs-2"%>
        </div></br><br/>

        <div class = "field">
          <label>URL</label>（http又はhttpsから始まるURLをご入力願います） <span class="recommendation">推奨</span><br/>
          <%= f.text_field :url, class:"col-xs-5" %>
        </div></br></br>

        <div class = "field">
          <%= f.label :自己紹介文 %><span class="recommendation"> 推奨</span><br/>
          <%= f.text_area :profile, size:'50x2',class:"body-text" ,placeholder: "※50文字以内で入力してください" %>
          <p class="text-count">現在の文字入力数：0文字</p>
        </div>

        <div class = "field">
          <%= f.label :プロフィール写真 %>（縦横比率が同じ画像をご準備願います）
          <%= f.attachment_field :image %>
        </div></br>

        <div class="actions">
          <%= f.submit "以上の情報で更新する", class: "btn btn-info col-xs-3" %>
        </div>
      <% end %></br></br>

        <div class="actions">
          <%= link_to "パスワードを変更する", edit_lawyer_registration_path(current_lawyer), class: "btn btn-success col-xs-3" %><span class="col-xs-1"></span><%= link_to "退会する", lawyer_withdraw_path(current_lawyer), class: "btn btn-danger col-xs-1" %>
        </div></br></br></br>

        <div class="actions">
          <%= link_to lawyer_path(current_lawyer) do %><span class="each_link">< 更新せずに戻る</span><% end %>
        </div>

    </div>
  </div>
</div>

app/views/lawyers/lawyers/show.html.erb
<div class="container yield">
  <div class="row">

    <div class="col-xs-12 center">
      <% if lawyer_signed_in? %>
        <h2><span class="lawyer_mypage">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fas fa-user-tie"></i>&nbsp;&nbsp;&nbsp;マ&nbsp;イ&nbsp;ペ&nbsp;ー&nbsp;ジ&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></h2>
      <% else %>
        <h2><span class="subject">&nbsp;&nbsp;<i class="fas fa-user-tie"></i>&nbsp;先生の情報を見る&nbsp;<i class="fas fa-user-tie"></i>&nbsp;&nbsp;</span></h2>
      <% end %><br/><br/>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-4"><br/>
      <%= render 'info', lawyer: @lawyer %>
    </div>
    <div class="col-xs-1"></div>
    <div class="col-xs-7">
      <%= render 'list', trues: @true_comments, comments:@comments, references: @true_references, lawyer: @lawyer %>
    </div>
  </div>
</div>

app/views/lawyers/lawyers/withdraw.html.erb
<div class="container bottom">
  <div class="row">

    <div class="withdraw">
      <h3>本当に退会してよろしいでしょうか？</h3><br/>

          同じメールアドレスでの再度の登録は不可能となります。<br/>
          パスワードを変更されたい場合は、<%= link_to "こちら", edit_lawyer_registration_path(current_lawyer) %>からお願い致します。<br/>
          退会しても回答投稿のデータは削除されませんので、御了承願います。</br>
          それでも退会する場合は、「退会する」をクリック願います。<br/><br/>

      <div class="actions">
        <span style="padding-right:100px;"><%= link_to "退会をやめる", lawyer_path(current_lawyer), class:"btn btn-warning" %></span>
        <span><%= link_to "退会する", lawyer_path(current_lawyer), data: { confirm: "本当に退会しますか?" }, method: :delete ,class:"btn btn-danger" %></span>
      </div>
    </div>

  </div>
</div>