config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#top"
  get "home/about"
  get 'home/thanks' => 'home#thanks', as: 'thanks'


  devise_for :admin
  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      member do
        patch 'restore'
      end
    end
    resources :lawyers, only: [:index, :show, :destroy] do
      member do
        patch 'restore'
      end
    end
    resources :categories, only: [:index, :create, :edit, :update]
    resources :comments, only: [:destroy]
    resources :troubles, only: [:destroy]
    resources :inquiries, only: [:index, :show, :destroy]
  end


  devise_for :lawyers, :controllers => {
  :registrations => 'lawyers/registrations'
  }
  scope module: :lawyers do
    get 'lawyers/:id/withdraw' => 'lawyers#withdraw',as: 'lawyer_withdraw'
    get 'lawyers/:id/map' => 'map#show',as: 'map'
    resources :lawyers, only: [:show, :edit, :update, :destroy]
    resources :comments, only: [:new, :create] do
      collection do
        get :confirm
        post :confirm
        post :new, path: :new, as: :new, action: :back
      end
    end
  end


  devise_for :users, :controllers => {
  :registrations => 'users/registrations'
  }
  scope module: :users do
    get 'users/:id/withdraw' => 'users#withdraw',as: 'user_withdraw'
    resources :troubles, only: [:index, :new, :create, :show] do
      collection do
        get :confirm
        post :confirm
        post :new, path: :new, as: :new, action: :back
      end
    end
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :comments, only: [] do
      resource :references, only: [:create, :destroy]
    end
    resources :references, only: [:index]
  end

    resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
    resources :inquiries, only: [:new, :create] do
      collection do
        get :thanks
      end
  end


end

app/models/trouble.rb
class Trouble < ApplicationRecord

  belongs_to :user, -> {with_deleted}
  belongs_to :category, optional: true

  has_many :comments, dependent: :destroy

  attachment :image

  validates :title, presence: true, length: {maximum: 20}
  validates :body ,presence: true, length: {maximum: 2000}
  validates :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :troubles
  has_many :references
  has_many :rooms, dependent: :destroy

  def chat(lawyer_id)
    troubles.joins(:comments).where(comments: { lawyer_id: lawyer_id }).group("comments.id").count
  end

  attachment :image

  enum prefecture: {北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,新潟県:15,
  	富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,岐阜県:21,静岡県:22,愛知県:23,三重県:24,滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,鳥取県:31,
  	島根県:32,岡山県:33,広島県:34,山口県:35,徳島県:36,香川県:37,愛媛県:38,高知県:39,福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47 }

  enum age: {十九歳以下:1, 二十歳代:2, 三十歳代:3, 四十歳代:4, 五十歳代:5, 六十歳代:6, 七十歳以上:7 }

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :nickname, presence: true, uniqueness: true
  validates :sex, inclusion: { in: [true, false] }
  validates :age, presence: true
  validates :prefecture, presence: true
  validates :city, presence: true

  acts_as_paranoid
end

app/controllers/admin/troubles_controller.rb
class Admin::TroublesController < ApplicationController

    before_action :authenticate_admin!

    def destroy
       trouble = Trouble.find(params[:id])
       trouble.destroy
       redirect_to troubles_path
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

    before_action :authenticate_admin!

    def index
       @users = User.all.with_deleted.order(created_at: :desc).page(params[:page]).per(10)
       @user_all = User.all.with_deleted
    end

    def show
       @user = User.with_deleted.find(params[:id])
    end

    def restore
       @user = User.with_deleted.find(params[:id])
       @user.restore
       redirect_to admin_user_path(@user)
    end

    def destroy
       @user = User.with_deleted.find(params[:id])
       @user.destroy
       redirect_to admin_user_path(@user)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/references_controller.rb
class Users::ReferencesController < ApplicationController

    before_action :authenticate_user!

    def index
      @true_references = []
      current_user.references.order(created_at: :desc).each do |reference|
        if reference.comment.trouble.category.is_active == true
        @true_references << reference
        end
      @references = Kaminari.paginate_array(@true_references).page(params[:page])
      end
    end

    def create
       @comment = Comment.find(params[:comment_id])
       reference = current_user.references.new(comment_id: @comment.id)
       reference.save
    end

    def destroy
       @comment = Comment.find(params[:comment_id])
       reference = current_user.references.find_by(comment_id: @comment.id)
       reference.destroy
    end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :sex, :age, :prefecture, :city])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/troubles_controller.rb
class Users::TroublesController < ApplicationController

    before_action :login, only: [:index]
    before_action :true_category, only: [:index]
    before_action :true_trouble, only: [:show]
    before_action :user_login, only: [:new, :confirm, :create, :back]
    before_action :true_categories, only: [:index, :new, :confirm, :create, :back]

    def index
        @categories = Category.all
          if params[:category_id].nil?
            troubles = Trouble.all.order(created_at: :desc)
            @true_troubles =[]
            troubles.each do |trouble|
              if trouble.category.is_active == true
                @true_troubles << trouble
              end
            end
            @troubles = Kaminari.paginate_array(@true_troubles).page(params[:page])
          else
            @category = Category.find(params[:category_id])
            @troubles = @category.troubles.order(created_at: :desc).page(params[:page])
          end
    end

    def new
       @trouble = Trouble.new
       @categories = Category.all
    end

    def confirm
       @trouble = Trouble.new(trouble_params)
       @trouble.user_id = current_user.id
         return if @trouble.valid?
           @categories = Category.all
           render :new
    end

    def back
       @trouble = Trouble.new(trouble_params)
       @categories = Category.all
         render :new
    end

    def create
       @trouble = Trouble.new(trouble_params)
       @trouble.user_id = current_user.id
         if @trouble.save
         	redirect_to @trouble
         else
         	render 'confirm'
         end
    end

    def show
       @trouble = Trouble.find(params[:id])
       @comments = @trouble.comments.order(created_at: :desc)
    end


    private
      def trouble_params
      	 params.require(:trouble).permit(:title, :body, :image, :category_id)
      end

      def login
      	unless user_signed_in? || lawyer_signed_in? || admin_signed_in?
      	  redirect_to root_path
      	end
      end

      def true_category
        unless params[:category_id].nil?
          category = Category.find(params[:category_id])
          if category.is_active == false
            redirect_to troubles_path
          end
        end
      end

      def true_trouble
        trouble = Trouble.find(params[:id])
        if trouble.category.is_active == false
          redirect_to troubles_path
        end
      end

      def user_login
    	  unless user_signed_in?
    	    redirect_to troubles_path
    	  end
      end

      def true_categories
        categories = Category.all
         @true_categories = []
         categories.each do |c|
           if c.is_active == true
             @true_categories << c
           end
         end
      end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

    before_action :correct_user, only: [:edit, :update, :withdraw, :destroy]
    before_action :login_model, only: [:show]

    def show
       @user = User.with_deleted.find(params[:id])
       @true_troubles = []
         @user.troubles.order(created_at: :desc).each do |trouble|
           if trouble.category.is_active == true
             @true_troubles << trouble
           end
         end
       @troubles = Kaminari.paginate_array(@true_troubles).page(params[:page])
    end

    def edit
       @user = User.find(current_user.id)
    end

    def update
       @user = User.find(current_user.id)
         if @user.update(user_params)
           redirect_to user_path(current_user)
         else
          render 'edit'
         end
    end

    def withdraw
    end

    def destroy
       user = User.find(current_user.id)
       user.destroy
       redirect_to thanks_path
    end

    private

      def user_params
        params.require(:user).permit(:name, :name_kana, :nickname, :age, :prefecture, :city, :image, :email)
      end

      def correct_user
        user = User.find(params[:id])
          if user_signed_in?
            if current_user.id != user.id
              redirect_to edit_user_path(current_user)
            end
          elsif lawyer_signed_in?
              redirect_to edit_lawyer_path(current_lawyer)
          else
              redirect_to root_path
          end
      end

      def login_model
        user = User.with_deleted.find(params[:id])
          if user.deleted_at == nil
            if user_signed_in?
              if current_user.id != user.id
                redirect_to user_path(current_user)
              end
            elsif lawyer_signed_in?
              @users = []
                current_lawyer.comments.each do |comment|
                @users << comment.trouble.user.id
            end
            elsif admin_signed_in?
            else
                redirect_to root_path
            end
          else
            if user_signed_in?
                redirect_to user_path(current_user)
            elsif lawyer_signed_in?
                redirect_to lawyer_path(current_lawyer)
            elsif admin_signed_in?
            else
                redirect_to root_path
            end
          end
      end

end

app/helpers/admin/troubles_helper.rb
module Admin::TroublesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/references_helper.rb
module Users::ReferencesHelper
end

app/helpers/users/troubles_helper.rb
module Users::TroublesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/users/troubles/confirm.html.erb
<div class = "container yield">
  <div class = "row">

    <div class="col-xs-12 center">
      <h2><span class = "subject">&nbsp;&nbsp;&nbsp;ー&nbsp;投稿内容を確認する&nbsp;ー&nbsp;&nbsp;&nbsp;</span></h2></br>
        <div>
          <% if @trouble.errors.any? %>
            <div class= "error">
              <div id="error_explanation">
                <h3>
                  <%= pluralize(@trouble.errors.count, "error") %>
                  prohibited this trouble from being saved:
                </h3>
                  <% @trouble.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                  <% end %>
              </div>
            </div>
          <% end %>
        </div>
    </div>


    <div class="col-xs-8 col-xs-offset-2 center">
      <h4 class="required">※ 一度投稿すると編集・削除することはできませんので、よくご確認願います!!</h4>
    </div>

    <div class="col-xs-6 col-xs-offset-3 frame">
        <label class="col-xs-3">相談者の名前</label>
          <p class ="col-xs-9"><%= @trouble.user.nickname %></p>
        <label class="col-xs-3">カテゴリー</label>
          <p class ="col-xs-9"><%= @trouble.category.name %></p>
        <label class="col-xs-12">説明写真</label>
          <span class ="col-xs-12 text-center"><%= attachment_image_tag @trouble, :image, class: "image_tag" %></span>
        <label class="col-xs-12"><br/>タイトル</label>
          <span class ="col-xs-12"><%= @trouble.title %></span>
        <label class="col-xs-12"><br/>投稿内容</label>
          <span class ="col-xs-12"><%= safe_join(@trouble.body.split("\n"),tag(:br)) %></span>
    </div>

    <div class="actions col-xs-6 col-xs-offset-3">

      <%= form_for(@trouble, url: troubles_path) do |f| %>

        <%= f.hidden_field :category_id, :value => @trouble.category_id %>
        <%= f.hidden_field :title, :value => @trouble.title %>
        <%= f.hidden_field :body, :value => @trouble.body %>
        <span class="attachment_field"><%= f.attachment_field :image, :value => @trouble.image %></span>
        <%= f.submit "内容を確認した上で、投稿する", class:"btn btn-success col-xs-12" %>

      <% end %>

    </div>

    <div class="actions col-xs-6 col-xs-offset-3">

      <%= form_for(@trouble, url: new_troubles_path) do |f| %>

        <%= f.hidden_field :category_id, :value => @trouble.category_id %>
        <%= f.hidden_field :title, :value => @trouble.title %>
        <%= f.hidden_field :body, :value => @trouble.body %>
        <span class="attachment_field"><%= f.attachment_field :image, :value => @trouble.image %></span>
        <%= f.submit "内容を訂正する", class:"btn btn-primary col-xs-12" %>

      <% end %>
    </div>

  </div>
</div>

app/views/users/troubles/index.html.erb
<div class = "container yield">

  <div class = "row">
  	<div class="col-xs-12 center">
      <h2><span class = "subject">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="far fa-list-alt"></i>&nbsp;&nbsp;皆の相談一覧（
      	  <% if @category != nil %>
		    <%= @category.name %>：全 <%= @category.troubles.count %> 件
		  <%else%>
				全 <%= @true_troubles.count %> 件
		  <%end%>）&nbsp;&nbsp;
	  </span></h2></br>
    </div>
  </div>

  <div class = "row">
    <div class="col-xs-8 col-xs-offset-4">
      <%= form_with( url: troubles_path, method: :get, local:true) do |f| %>
        カテゴリー別に見る➡️
        <%= f.collection_select :category_id, @true_categories, :id, :name %>
        <%= button_tag :type => "submit", class: "btn btn-primary" do %>&nbsp;&nbsp;<i class="fa fa-search"></i>&nbsp;&nbsp;<% end %>
          <% if @category != nil %>
            <%= link_to '全ての投稿を見る', troubles_path, class: "btn btn-warning col-xs-offset-1" %>
          <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-xs10 col-xs-offset-1">
  	<h4>ー<%= @troubles.count %>件を表示中ー（新着順）</h4>
  </div>

    <table ~~~ class = "table">

      <colgroup>
         <col style = "width:7%;">
         <col style = "width:15%;">
         <col style = "width:15%;">
         <col style = "width:28%;">
         <col style = "width:28%;">
         <col style = "width:7%;">
      </colgroup>

	    <tr>
	      <th></th>
	      <th>名前</th>
		  <th>カテゴリー</th>
		  <th>タイトル</th>
		  <th>内容</th>
		  <th class="center">回答数</th>
	    </tr>

	  <% @troubles.each do |trouble| %>
	    <tr>
	      <td>
	      	<% if trouble.user.deleted_at == nil %>
	      	  <%= attachment_image_tag trouble.user, :image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
	      	<% else %>
	      	  <%= image_tag "no_image.jpg",size:"40x40" %>
	      	<% end %>
	      </td>
	      <td>
	      	<% if trouble.user.deleted_at == nil %>
	      	  <% if admin_signed_in? || lawyer_signed_in? %>
	      	    <%= link_to user_path(trouble.user) do %><span class="each_link"><%= trouble.user.nickname %></span><% end %> 様
	      	  <% else %>
	      	    <%= trouble.user.nickname %> 様
	      	  <% end %>
	      	<% else %>
	      	  退会したユーザー
	      	<% end %>
	      </td>
		  <td>
		  	<%= trouble.category.name %>
		  </td>
		  <td>
		    <%= link_to trouble_path(trouble) do %><span class="each_link"><%= trouble.title %></span><% end %>
		  </td>
		  <td>
            <%= trouble.body.truncate(20) %>
		  </td>
		  <td class="center">
		  	<%= trouble.comments.count %>件
		  </td>
	    </tr>
	  <%end%>
    </table>

	<div class = "col-xs-12 center"><br/>
	  <%= paginate @troubles, class: "paginate" %>
    </div>
</div>

app/views/users/troubles/new.html.erb
<div class = "container yield">
  <div class = "row">

  	<div class="col-xs-12 center">
      <h2><span class = "subject">&nbsp;&nbsp;&nbsp;ー&nbsp;法専門家に相談する&nbsp;ー&nbsp;&nbsp;&nbsp;</span></h2></br>
        <div>
          <% if @trouble.errors.any? %>
            <div class= "error">
              <div id="error_explanation">
                <h3>
                  <%= pluralize(@trouble.errors.count, "error") %>
                  prohibited this trouble from being saved:
                </h3>
                  <% @trouble.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                  <% end %>
              </div>
            </div>
          <% end %>
        </div>
    </div>

    <div class="col-xs-6 col-xs-offset-3">

      <%= form_for(@trouble, url: confirm_troubles_path) do |f| %>

      　<div class="field">
          <%= f.label :カテゴリー, class:"col-xs-3" %>
          <%= f.collection_select :category_id, @true_categories, :id, :name, :prompt => "選択" %>
        </div></br>

        <div class="field">
          <%= f.label :説明の写真, class:"col-xs-12" %>
          <% if @trouble.image != nil %>
            <span class ="col-xs-12"><%= attachment_image_tag @trouble, :image, class: "image_tag" %></span>
          <% end %>
          <%= f.attachment_field :image, class:"col-xs-6" %>
        </div></br></br>

        <div class="field"></br>
          <%= f.label :タイトル, class:"col-xs-12" %><br/>
          <%= f.text_field :title, class:"col-xs-12",placeholder: "※20文字以内でご入力願います" %>
        </div></br></br>

        <div class="field">
          <%= f.label :投稿内容, class:"col-xs-12" %>
          <%= f.text_area :body, class:"col-xs-12 body-text",size:'15x15',placeholder: "※2000文字以内でご入力願います" %>
          <p class="text-count">現在の文字入力数：0文字</p>
        </div>

    </div>

    <div class="col-xs-6 col-xs-offset-3">

        <div class="actions">
          <%= f.submit "投稿内容を確認する", class:"btn btn-primary col-xs-12" %>
        </div>

      <% end %>
    </div>

  </div>
</div>

app/views/users/troubles/show.html.erb
<div class = "container yield">

    <div class="col-xs-12 center">
      <h2><span class = "subject">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ー&nbsp;&nbsp;&nbsp;相&nbsp;&nbsp;談&nbsp;&nbsp;内&nbsp;&nbsp;容&nbsp;&nbsp;&nbsp;ー&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></h2></br>
    </div>

    <div class="col-xs-6 col-xs-offset-3 frame">

        <label class="col-xs-3">相談者の名前</label>
          <p class ="col-xs-9">
            <% if @trouble.user.deleted_at == nil %>
              <% if admin_signed_in? || lawyer_signed_in? %>
                <%= link_to user_path(@trouble.user) do %><span class="each_link"><%= @trouble.user.nickname %></span><% end %> 様
              <% else %>
                <%= @trouble.user.nickname %> 様
              <% end %>
            <% else %>
              退会したユーザー
            <% end %>
          </p>

        <label class="col-xs-3">カテゴリー</label>
          <p class ="col-xs-9"><%= @trouble.category.name %></p>

        <label class="col-xs-3">投稿日時</label>
          <p class ="col-xs-9"><%= @trouble.created_at.strftime('%Y年%m月%d日 %H時%M分') %></p>

      <% if @trouble.image_id != nil %>
        <label class="col-xs-12">説明写真</label>
          <span class ="col-xs-12 text-center"><%= attachment_image_tag @trouble, :image, class: "image_tag" %></span>
      <% end %>

        <label class="col-xs-12"><br/>タイトル</label>
          <span class ="col-xs-12"><%= @trouble.title %></span>

        <label class="col-xs-12"><br/>投稿内容</label>
          <span class ="col-xs-12"><%= safe_join(@trouble.body.split("\n"),tag(:br)) %></span>

      <% if admin_signed_in? %>
        <div class="right"><br/>
          <%= link_to "強制削除する", admin_trouble_path(@trouble), method: :delete, "data-confirm"  => "[要確認!!]コメントがあれば一緒に削除されてしまいます!!本当に削除しますか？", class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>

    <% if lawyer_signed_in? %>
      <% if @trouble.user.deleted_at == nil %>
        <% if Comment.exists?(trouble_id: @trouble.id, lawyer_id: current_lawyer.id) %>
          <div class="col-xs-6 col-xs-offset-3 actions">
            <h4 class="required", style="text-align:center;">※既に回答して頂いているので、再度の回答はできません。</h4>
          </div>
        <% else %>
          <div class="col-xs-6 col-xs-offset-3 actions"><br/>
            <%= link_to "この相談に回答する", new_comments_path(trouble_id: @trouble.id), class:"btn btn-primary col-xs-12" %><br/>
          </div>
        <% end %>
      <% end %>
    <% end %>


    <% if @trouble.comments.count > 0 %>

      <div class="col-xs-6 comments"></div>

      <div class="col-xs-6 col-xs-offset-3 center commentitle">
        <h2 style="margin-left: 40px;"><span class="lawyer_mypage">&nbsp;&nbsp;ー&nbsp;&nbsp;&nbsp;回&nbsp;答（全&nbsp;<%= @trouble.comments.count %>&nbsp;件）ー&nbsp;&nbsp;</span></h2>
      </div>

      <% @comments.each do |comment| %>
        <div class="col-xs-6 col-xs-offset-3 frame comment">

          <label class="col-xs-3">回答者</label>
            <p class ="col-xs-9">
              <% if comment.lawyer.deleted_at == nil %>
                <% if admin_signed_in?  %>
                  <%=link_to lawyer_path(comment.lawyer_id) do %><span class="each_link"><%= comment.lawyer.name %></span><% end %> 様より
                <% elsif lawyer_signed_in? %>
                  <% if current_lawyer.id == comment.lawyer.id %>
                    <%=link_to lawyer_path(comment.lawyer_id) do %><span class="each_link"><%= comment.lawyer.name %></span><% end %> 様より
                  <% else %>
                    <%= comment.lawyer.prefecture %>の<%= comment.lawyer.profession %>の方より
                  <% end %>
                <% elsif user_signed_in? %>
                    <%=link_to lawyer_path(comment.lawyer_id) do %><span class="each_link"><%= comment.lawyer.name %></span><% end %> 様より
                <% end %>
              <% else %>
                退会したユーザー
              <% end %>
            </p>

          <label class="col-xs-3">回答日時</label>
            <p class ="col-xs-9"><%= comment.created_at.strftime('%Y年%m月%d日 %H時%M分') %></p>

          <label class="col-xs-12">回答内容</label>
            <span class ="col-xs-12"><%= safe_join(comment.comment.split("\n"),tag(:br)) %></span>

        <% if admin_signed_in? %>
          <div class="col-xs-12 right"><br/>
            <span class="glyphicon glyphicon-thumbs-up" style="color:#000000;">参考になった<%= comment.references.count %></span>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "強制削除する", admin_comment_path(comment), method: :delete, "data-confirm"  => "[要確認!!]本当に削除しますか？", class: "btn   btn-danger" %>
          </div>
        <% elsif user_signed_in? %>
          <div class="col-xs-12 right"><br/>
            <%= render 'users/references/reference', comment: comment %>
          </div>
        <% else %>
          <div class="col-xs-12 right"><br/>
            <span class="glyphicon glyphicon-thumbs-up" style="color:#000000;">参考になった<%= comment.references.count %></span>
          </div>
        <% end %>

        </div>
      <% end %>

    <% end %>

</div>