config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#top"
  get "home/about"
  get 'home/thanks' => 'home#thanks', as: 'thanks'


  devise_for :admin
  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      member do
        patch 'restore'
      end
    end
    resources :lawyers, only: [:index, :show, :destroy] do
      member do
        patch 'restore'
      end
    end
    resources :categories, only: [:index, :create, :edit, :update]
    resources :comments, only: [:destroy]
    resources :troubles, only: [:destroy]
    resources :inquiries, only: [:index, :show, :destroy]
  end


  devise_for :lawyers, :controllers => {
  :registrations => 'lawyers/registrations'
  }
  scope module: :lawyers do
    get 'lawyers/:id/withdraw' => 'lawyers#withdraw',as: 'lawyer_withdraw'
    get 'lawyers/:id/map' => 'map#show',as: 'map'
    resources :lawyers, only: [:show, :edit, :update, :destroy]
    resources :comments, only: [:new, :create] do
      collection do
        get :confirm
        post :confirm
        post :new, path: :new, as: :new, action: :back
      end
    end
  end


  devise_for :users, :controllers => {
  :registrations => 'users/registrations'
  }
  scope module: :users do
    get 'users/:id/withdraw' => 'users#withdraw',as: 'user_withdraw'
    resources :troubles, only: [:index, :new, :create, :show] do
      collection do
        get :confirm
        post :confirm
        post :new, path: :new, as: :new, action: :back
      end
    end
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :comments, only: [] do
      resource :references, only: [:create, :destroy]
    end
    resources :references, only: [:index]
  end

    resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
    resources :inquiries, only: [:new, :create] do
      collection do
        get :thanks
      end
  end


end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :lawyer, -> {with_deleted}
  belongs_to :trouble

  has_many :references, dependent: :destroy
  has_many :reference_users, through: :references, source: :user

  def referenced_by?(user)
    references.where(user_id: user.id).exists?
  end

  validates :comment, presence: true, length: { maximum: 2000 }
end

app/models/lawyer.rb
class Lawyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  has_many :comments
  has_many :rooms

  enum profession: {弁護士:1, 司法書士:2, 行政書士:3, 会計士:4, 税理士:5}
  enum age: {二十歳代:1, 三十歳代:2, 四十歳代:3, 五十歳代:4, 六十歳以上:5 }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :office, presence: true
  validates :profession, presence: true
  validates :sex, inclusion: { in: [true, false] }
  validates :age, presence: true
  validates :profile, length: { maximum: 50 }
  validates :postal_code, presence: true, length: { is: 7 }
  validates :prefecture, presence: true
  validates :address, presence: true
  validates :phone_number, length: { minimum: 10, maximum: 11 }, allow_blank: true
  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true

  acts_as_paranoid
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

    before_action :authenticate_admin!

    def destroy
       comment = Comment.find(params[:id])
       comment.destroy
       redirect_to trouble_path(comment.trouble_id)
    end

end

app/controllers/admin/lawyers_controller.rb
class Admin::LawyersController < ApplicationController

    before_action :authenticate_admin!

    def index
       @lawyers = Lawyer.all.with_deleted.order(created_at: :desc).page(params[:page]).per(10)
       @lawyer_all = Lawyer.all.with_deleted
    end

    def show
       @lawyer = Lawyer.with_deleted.find(params[:id])
    end

    def restore
       @lawyer = Lawyer.with_deleted.find(params[:id])
       @lawyer.restore
       redirect_to admin_lawyer_path(@lawyer)
    end

    def destroy
       @lawyer = Lawyer.with_deleted.find(params[:id])
       @lawyer.destroy
       redirect_to admin_lawyer_path(@lawyer)
    end

end

app/controllers/lawyers/comments_controller.rb
class Lawyers::CommentsController < ApplicationController

    before_action :lawyer_new, only: [:new]
    before_action :lawyer_create, only:[:confirm, :create, :back]

    def new
       @comment = Comment.new
       @trouble = Trouble.find(params[:trouble_id])
       @comment.trouble_id = params[:trouble_id]
    end

    def confirm
       @comment = Comment.new(comment_params)
       @comment.lawyer_id = current_lawyer.id
       return if @comment.valid?
         @trouble = Trouble.find(@comment.trouble_id)
         render :new
    end

    def back
       @comment = Comment.new(comment_params)
       @trouble = Trouble.find(@comment.trouble_id)
       render :new
    end

    def create
       @comment = Comment.new(comment_params)
       @comment.lawyer_id = current_lawyer.id
         if @comment.save
         	redirect_to trouble_path(@comment.trouble_id)
         else
         	render 'confirm'
         end
    end

    private
      def comment_params
      	 params.require(:comment).permit(:comment, :trouble_id)
      end

      def lawyer_new
      	trouble = Trouble.find(params[:trouble_id])
      	if lawyer_signed_in?
      	  if trouble.user.deleted_at == nil
      	    #回答は一人一度限りを設定
      	  	if Comment.exists?(trouble_id: trouble.id, lawyer_id: current_lawyer.id)
      	  	  redirect_to trouble_path(trouble)
      	    end
      	  else
      	  	redirect_to trouble_path(trouble)
      	  end
        else
      	  redirect_to troubles_path
      	end
      end

      def lawyer_create
      	comment = Comment.new(comment_params)
      	trouble = Trouble.find(comment.trouble_id)
      	if lawyer_signed_in?
      	  if trouble.user.deleted_at == nil
      	    #回答は一人一度限りを設定
      	    if Comment.exists?(trouble_id: trouble.id, lawyer_id: current_lawyer.id)
      	  	  redirect_to trouble_path(trouble)
      	    end
      	  else
      	  	redirect_to trouble_path(trouble)
      	  end
        else
      	  redirect_to troubles_path
      	end
      end

end

app/controllers/lawyers/confirmations_controller.rb
# frozen_string_literal: true

class Lawyers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/lawyers/lawyers_controller.rb
class Lawyers::LawyersController < ApplicationController

    before_action :correct_lawyer, only: [:edit, :update, :withdraw, :destroy]
    before_action :login_model, only: [:show]

    def show
       @lawyer = Lawyer.with_deleted.find(params[:id])
       @true_comments = []
       reference = []
         @lawyer.comments.order(created_at: :desc).each do |comment|
           if comment.trouble.category.is_active == true
             @true_comments << comment
             reference << comment.references.count
             @true_references = reference.sum
           end
       end
       @comments = Kaminari.paginate_array(@true_comments).page(params[:page]).per(15)
    end

    def edit
       @lawyer = Lawyer.find(current_lawyer.id)
    end

    def update
       @lawyer = Lawyer.find(current_lawyer.id)
         if @lawyer.update(lawyer_params)
           redirect_to lawyer_path(current_lawyer)
         else
           render 'edit'
         end
    end

    def withdraw
    end

    def destroy
       lawyer = Lawyer.find(current_lawyer.id)
       lawyer.destroy
       redirect_to thanks_path
    end

    private
      def lawyer_params
        params.require(:lawyer).permit(:name, :name_kana, :office, :profession, :age, :postal_code, :prefecture, :address, :latitude, :longitude, :profile, :phone_number, :url, :image, :email)
      end

      def correct_lawyer
        lawyer = Lawyer.find(params[:id])
          if lawyer_signed_in?
            if current_lawyer.id != lawyer.id
              redirect_to edit_lawyer_path(current_lawyer)
            end
          elsif user_signed_in?
              redirect_to edit_user_path(current_user)
          else
              redirect_to root_path
          end
      end

      def login_model
        lawyer = Lawyer.with_deleted.find(params[:id])
          if lawyer.deleted_at == nil
            if lawyer_signed_in?
              if current_lawyer.id != lawyer.id
                redirect_to lawyer_path(current_lawyer)
              end
            elsif user_signed_in?
                rooms = current_user.rooms
                #自分が入ってるroomの相手のidを格納する
                @lawyer_ids = []
                   rooms.each do |room|
                   @lawyer_ids << room.lawyer_id
                end
            elsif admin_signed_in?
            else
                redirect_to root_path
            end
          else
            if lawyer_signed_in?
                redirect_to lawyer_path(current_lawyer)
            elsif user_signed_in?
                redirect_to user_path(current_user)
            elsif admin_signed_in?
            else
                redirect_to root_path
            end
          end
      end

end

app/controllers/lawyers/map_controller.rb
class Lawyers::MapController < ApplicationController

    before_action :login_model, only: [:show]

    def show
       @lawyer = Lawyer.with_deleted.find(params[:id])
    end


    private
      def login_model
        lawyer = Lawyer.with_deleted.find(params[:id])
          if lawyer.deleted_at == nil
    	    unless user_signed_in? || admin_signed_in?
    	    	if lawyer_signed_in?
    	    	  if current_lawyer.id != lawyer.id
    	    	  	redirect_to lawyer_path(current_lawyer)
    	    	  end
    	    	else
    	          redirect_to root_path
    	        end
          end
          else
            unless admin_signed_in?
              if lawyer_signed_in?
                redirect_to lawyer_path(current_lawyer)
              elsif user_signed_in?
                redirect_to user_path(current_user)
              else
                redirect_to root_path
              end
            end
          end
      end
end

app/controllers/lawyers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Lawyers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/lawyers/passwords_controller.rb
# frozen_string_literal: true

class Lawyers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/lawyers/registrations_controller.rb
# frozen_string_literal: true

class Lawyers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :office, :profession, :sex, :age, :postal_code, :prefecture, :address, :latitude, :longitude, :phone_number, :url])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/lawyers/sessions_controller.rb
# frozen_string_literal: true

class Lawyers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/lawyers/unlocks_controller.rb
# frozen_string_literal: true

class Lawyers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/lawyers_helper.rb
module Admin::LawyersHelper
end

app/helpers/lawyers/comments_helper.rb
module Lawyers::CommentsHelper
end

app/helpers/lawyers/lawyers_helper.rb
module Lawyers::LawyersHelper
end

app/helpers/lawyers/map_helper.rb
module Lawyers::MapHelper
end

app/views/lawyers/comments/confirm.html.erb
<div class = "container yield">
  <div class = "row">

    <div class="col-xs-12 center">
      <h2><span class = "subject">&nbsp;&nbsp;&nbsp;ー&nbsp;回答内容を確認する&nbsp;ー&nbsp;&nbsp;&nbsp;</span></h2></br>
        <div>
          <% if @comment.errors.any? %>
            <div class= "error">
              <div id="error_explanation">
                <h3>
                  <%= pluralize(@comment.errors.count, "error") %>
                  prohibited this comment from being saved:
                </h3>
                  <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                  <% end %>
              </div>
            </div>
          <% end %>
        </div>
    </div>

    <div class="col-xs-8 col-xs-offset-2 center">
        <h4 class="required">※ 一度投稿すると編集・削除することはできませんので、よくご確認願います!!</h4><br/>
    </div>

    <div class="col-xs-6 col-xs-offset-3 frame">
        <label class="col-xs-12">回答内容</label><br/><br/>
          <span class ="col-xs-12"><%= safe_join(@comment.comment.split("\n"),tag(:br)) %></span>
    </div>

    <div class="actions col-xs-6 col-xs-offset-3">

      <%= form_for(@comment, url: comments_path) do |f| %>

        <%= f.hidden_field :comment, :value => @comment.comment %>
        <%= f.hidden_field :trouble_id, :value => @comment.trouble.id %>

        <%= f.submit "内容を確認した上で、投稿する", class:"btn btn-success col-xs-12" %>

      <% end %>

    </div>

    <div class="actions col-xs-6 col-xs-offset-3">

      <%= form_for(@comment, url: new_comments_path) do |f| %>

        <%= f.hidden_field :comment, :value => @comment.comment %>
        <%= f.hidden_field :trouble_id, :value => @comment.trouble.id %>

        <%= f.submit "内容を訂正する", class:"btn btn-primary col-xs-12" %>

      <% end %>
    </div>

  </div>
</div>

app/views/lawyers/comments/new.html.erb
<div class = "container yield">
  <div class = "row">

  	<div class="col-xs-12 center">
      <h2><span class = "subject">&nbsp;&nbsp;&nbsp;ー&nbsp;相談に回答する&nbsp;ー&nbsp;&nbsp;&nbsp;</span></h2></br>
        <div>
          <% if @comment.errors.any? %>
            <div class= "error">
              <div id="error_explanation">
                <h3>
                  <%= pluralize(@comment.errors.count, "error") %>
                  prohibited this comment from being saved:
                </h3>
                  <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                  <% end %>
              </div>
            </div>
          <% end %>
        </div>
    </div>

    <div class="col-xs-6 col-xs-offset-3">
      <h4 class="required">※ 回答はお一人様一度限りとなりますので、ご注意願います。</h4>
    </div>

    <div class="col-xs-6 col-xs-offset-3">
      <div class="field">
        <%= form_for(@comment, url: confirm_comments_path) do |f| %>
          <%= f.label :回答内容, class:"col-xs-12" %>
          <%= f.text_area :comment, class:"col-xs-12 body-text",size:'15x15',placeholder: "※2000文字以内でご入力願います" %>
          <p class="text-count">現在の文字入力数：0文字</p>
          <%= f.hidden_field :trouble_id %>
      </div>
    </div>

    <div class="col-xs-6 col-xs-offset-3">

      <div class="actions">
          <%= f.submit "回答内容を確認する", class:"btn btn-primary col-xs-12" %>
        <% end %>
      </div>
    </div>

    <div class="col-xs-6 col-xs-offset-3 content center">
      <h3 style="margin-left: 40px;"><span class="user_mypage">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ー&nbsp;&nbsp;&nbsp;相&nbsp;&nbsp;談&nbsp;&nbsp;内&nbsp;&nbsp;容&nbsp;&nbsp;&nbsp;ー&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></h3>
    </div>

    <div class="col-xs-6 col-xs-offset-3 frame">

        <label class="col-xs-3">相談者の名前</label>
          <p class ="col-xs-9">
              <%= @trouble.user.nickname %> 様
          </p>

        <label class="col-xs-3">カテゴリー</label>
          <p class ="col-xs-9"><%= @trouble.category.name %></p>

        <label class="col-xs-3">投稿日時</label>
          <p class ="col-xs-9"><%= @trouble.created_at.strftime('%Y年%m月%d日 %H時%M分') %></p>

        <% if @trouble.image_id != nil %>
          <label class="col-xs-12">説明写真</label>
            <span class ="col-xs-12 text-center"><%= attachment_image_tag @trouble, :image, class: "image_tag" %></span>
        <% end %>

        <label class="col-xs-12"><br/>タイトル</label>
          <span class ="col-xs-12"><%= @trouble.title %></span>

        <label class="col-xs-12"><br/>投稿内容</label>
          <span class ="col-xs-12"><%= safe_join(@trouble.body.split("\n"),tag(:br)) %></span>

    </div>

  </div>
</div>