config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#top"
  get "home/about"
  get 'home/thanks' => 'home#thanks', as: 'thanks'


  devise_for :admin
  namespace :admin do
    resources :users, only: [:index, :show, :destroy] do
      member do
        patch 'restore'
      end
    end
    resources :lawyers, only: [:index, :show, :destroy] do
      member do
        patch 'restore'
      end
    end
    resources :categories, only: [:index, :create, :edit, :update]
    resources :comments, only: [:destroy]
    resources :troubles, only: [:destroy]
    resources :inquiries, only: [:index, :show, :destroy]
  end


  devise_for :lawyers, :controllers => {
  :registrations => 'lawyers/registrations'
  }
  scope module: :lawyers do
    get 'lawyers/:id/withdraw' => 'lawyers#withdraw',as: 'lawyer_withdraw'
    get 'lawyers/:id/map' => 'map#show',as: 'map'
    resources :lawyers, only: [:show, :edit, :update, :destroy]
    resources :comments, only: [:new, :create] do
      collection do
        get :confirm
        post :confirm
        post :new, path: :new, as: :new, action: :back
      end
    end
  end


  devise_for :users, :controllers => {
  :registrations => 'users/registrations'
  }
  scope module: :users do
    get 'users/:id/withdraw' => 'users#withdraw',as: 'user_withdraw'
    resources :troubles, only: [:index, :new, :create, :show] do
      collection do
        get :confirm
        post :confirm
        post :new, path: :new, as: :new, action: :back
      end
    end
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :comments, only: [] do
      resource :references, only: [:create, :destroy]
    end
    resources :references, only: [:index]
  end

    resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
    resources :inquiries, only: [:new, :create] do
      collection do
        get :thanks
      end
  end


end

app/models/category.rb
class Category < ApplicationRecord

  has_many :troubles, dependent: :destroy

  validates :name, presence: true
  validates :is_active, inclusion: { in: [true, false] }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

    before_action :authenticate_admin!

    def index
       @categories = Category.all
       @category = Category.new
    end

    def create
       @category = Category.new(category_params)
         if @category.save
            redirect_to admin_categories_path
         else @categories = Category.all
            render 'index'
         end
    end

    def edit
       @category = Category.find(params[:id])
    end

    def update
       @category = Category.find(params[:id])
         if @category.update(category_params)
            redirect_to admin_categories_path
         else
            render 'edit'
         end
    end

    private
      def category_params
        params.require(:category).permit(:name, :is_active)
      end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class = "container yield">
  <div class = "row">

    <div class="col-xs-12 center">
	    <h2><span class = "subject">&nbsp;&nbsp;カテゴリーを編集する&nbsp;&nbsp;</span></h2><br/>
        <h3>このカテゴリーには投稿が<%= @category.troubles.count %>件あります</h3>
          <% if @category.errors.any? %>
            <div class= "error">
              <div id="error_explanation">
                <h3>
                  <%= pluralize(@category.errors.count, "error") %>
                   prohibited this category from being saved:
                </h3>
                  <% @category.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                  <% end %>
              </div>
            </div>
          <% end %>
    </div>

    <div class="col-xs-6 col-xs-offset-4"><br/><br/>
      <%= form_for(@category, url: admin_category_path) do |f| %>

        <div class="form">
          <%= f.label :ジャンル, class:"col-xs-3" %>
          <%= f.text_field :name %>
        </div></br>

        <div class="form">
          <%= f.label :ステータス, class:"col-xs-3" %>
            <span class= "col-xs-2">
              <%= f.radio_button :is_active, true %>
          	  <%= f.label :有効 %>
            </span>
            <span class= "col-xs-2">
          	  <%= f.radio_button :is_active, false %>
          	  <%= f.label :無効 %>
            </span>
        </div></br></br></br>
    </div>
    <div class="col-xs-4 col-xs-offset-4">
      <%= f.submit "変更を保存", class: "btn btn-info col-xs-12" %>
    </div></br></br>
      <% end %></br></br>

    <div class = "col-xs-6 col-xs-offset-4"><br/><br/>
          <%= link_to "< 一覧へ戻る", admin_categories_path %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class = "container yield">
  <div class = "row">

  	<div class="col-xs-12 center">
      <h2><span class = "subject">&nbsp;&nbsp;カテゴリー一覧・追加&nbsp;&nbsp;</span></h2></br>
        <div>
          <% if @category.errors.any? %>
            <div class= "error">
              <div id="error_explanation">
                <h3>
                  <%= pluralize(@category.errors.count, "error") %>
                  prohibited this category from being saved:
                </h3>
                  <% @category.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                  <% end %>
              </div>
            </div>
          <% end %>
        </div>
    </div>

    <div class="col-xs-6 col-xs-offset-3">
  		<%= form_for(@category, url: admin_categories_path) do |f| %>

  		    <div class="field">
  		      <%= f.label :カテゴリー名, class:"col-xs-3" %>
  		      <%= f.text_field :name, class:"col-xs-5" %>
  		    </div></br></br>

          <div class="field">
            <%= f.label :ステータス, class:"col-xs-3" %>
              <span class= "col-xs-2">
  		          <%= f.radio_button :is_active, true %>
  		          <%= f.label :有効 %>
  		        </span>
  		        <span class= "col-xs-3">
  		          <%= f.radio_button :is_active, false %>
  		          <%= f.label :無効 %>
  		        </span>
  		        <span class= "col-xs-3">
  		          <%= f.submit "追加する" %>
  		        </span>
  		    </div>

  	 <% end %>
    </div>

  </div></br></br>

  <div class = "row">

  	<div class="col-xs-6 col-xs-offset-3">

  	    <table ~~~ class = "table">

          <colgroup>
             <col style = "width:30%;">
             <col style = "width:20%;">
             <col style = "width:30%;">
             <col style = "width:20%;">
          </colgroup>

  		    <tr class= "tr-color">
  			    <th class = "text-center">カテゴリー</th>
            <th class = "text-center">投稿数</th>
  			    <th class = "text-center">ステータス</th>
  			    <th></th>
  		    </tr>

  		  <% @categories.each do |category| %>
  		    <tr>
  			    <td class = "text-center"><%= category.name %></td>
            <td class = "text-center">
              <%= category.troubles.count %>件
            </td>
  			    <td class = "text-center">
  			      <% if category.is_active == true %>
  				      <p>有効</p>
  				    <%else%>
  				      <p>無効</p>
  				    <%end%>
  			    </td>
  			    <td>
  				    <%= link_to "編集する", edit_admin_category_path(category), class: "btn btn-success" %>
  			    </td>
  		    </tr>
  		  <%end%>
  	    </table>
    </div>
  </div>
</div>